/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobResponse { 
    id?: number;
    title?: string;
    description?: string;
    location?: string;
    status?: JobResponse.StatusEnum;
    salaryMin?: number;
    salaryMax?: number;
    createdAt?: string;
    updatedAt?: string;
}
export namespace JobResponse {
    export const StatusEnum = {
        Draft: 'DRAFT',
        Open: 'OPEN',
        Closed: 'CLOSED',
        Archived: 'ARCHIVED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


