/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    firstName: string;
    lastname: string;
    email: string;
    password: string;
    phone?: string;
    role?: RegisterRequest.RoleEnum;
}
export namespace RegisterRequest {
    export const RoleEnum = {
        RoleUser: 'ROLE_USER',
        RoleRecruiter: 'ROLE_RECRUITER',
        RoleAdmin: 'ROLE_ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


