/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobRequest { 
    title: string;
    description: string;
    location: string;
    status: JobRequest.StatusEnum;
    salaryMin: number;
    salaryMax: number;
}
export namespace JobRequest {
    export const StatusEnum = {
        Draft: 'DRAFT',
        Open: 'OPEN',
        Closed: 'CLOSED',
        Archived: 'ARCHIVED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


