/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthReponse } from '../model/models';
import { LoginRequest } from '../model/models';
import { RegisterRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<AuthReponse>;

    /**
     * 
     * 
     * @endpoint post /api/auth/register
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<AuthReponse>;

}
