/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthReponse } from '../model/models';
import { LoginRequest } from '../model/models';
import { LogoutRequest } from '../model/models';
import { RefreshTokenRequest } from '../model/models';
import { RegisterRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Login with email and password
     * 
     * @endpoint post /api/auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<AuthReponse>;

    /**
     * Logout — invalidate refresh token
     * Deletes the refresh token from the server so it can never be used again. The client must discard both the access token and refresh token after calling this endpoint.
     * @endpoint post /api/auth/logout
     * @param logoutRequest 
     */
    logout(logoutRequest: LogoutRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Refresh access token
     * Exchange a valid refresh token for a new access token + rotated refresh token pair. The old refresh token is invalidated immediately after use.
     * @endpoint post /api/auth/refresh
     * @param refreshTokenRequest 
     */
    refresh(refreshTokenRequest: RefreshTokenRequest, extraHttpRequestParams?: any): Observable<AuthReponse>;

    /**
     * Register new user
     * 
     * @endpoint post /api/auth/register
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<AuthReponse>;

}
