/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { JobRequest } from '../model/models';
import { JobResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface JobControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/jobs
     * @param jobRequest 
     */
    createJob(jobRequest: JobRequest, extraHttpRequestParams?: any): Observable<JobResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/jobs/{id}
     * @param id 
     */
    deleteJob(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/jobs/{id}
     * @param id 
     */
    getJob(id: number, extraHttpRequestParams?: any): Observable<JobResponse>;

    /**
     * 
     * 
     * @endpoint put /api/jobs/{id}
     * @param id 
     * @param jobRequest 
     */
    updateJob(id: number, jobRequest: JobRequest, extraHttpRequestParams?: any): Observable<JobResponse>;

}
