/**
 * Job Portal Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { JobRequest } from '../model/models';
import { JobResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface JobControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/jobs
     * @param jobRequest 
     */
    createJob(jobRequest: JobRequest, extraHttpRequestParams?: any): Observable<JobResponse>;

}
